default: &default
  adapter: postgresql
  pool: 5
  timeout: 5000

development:
  <<: *default
  database: audiopila_dev

test:
  <<: *default
  database: audiopila_test

production:
  <<: *default
  database: audiopila
